{{- if .Values.ethstats.secrets.isAwsSecretEnabled -}}
{{- $component := "ethstats" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-aws-secrets-class
  namespace: {{ include "linea-dev.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  secretObjects:
    - secretName: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-aws-sm-secret
      type: Opaque
      labels:
        {{- include "linea-dev.component.labels" (dict "component" $component "root" .) | nindent 8 }}
      data:
      - objectName: "ws_secret"
        key: "{{ .Values.ethstats.secrets.wsSecretName }}"
  parameters:
    {{- if .Values.global.region }}
    region: {{ .Values.global.region }}
    {{- end }}
    objects: |
      - objectName: "{{ .Values.ethstats.secrets.wsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "{{ .Values.ethstats.secrets.wsSecretName }}"
            objectAlias: "ws_secret"
{{- end }}