{{- $component := "ethstats" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}
  namespace: {{ include "linea-dev.namespace" . }}
  labels:
    {{- include "linea-dev.component.labels" (dict "component" $component "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.ethstats.replicaCount }}
  selector:
    matchLabels:
      {{- include "linea-dev.component.selectorLabels" (dict "component" $component "root" .) | nindent 6 }}
  template:
    metadata:
      {{- with include "linea-dev.component.annotations" (dict "component" $component "root" .) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linea-dev.component.labels.with.custom" (dict "component" $component "customLabels" .Values.ethstats.podLabels "root" .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "linea-dev.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ethstats.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ethstats
          image: "{{ .Values.ethstats.image.repository }}:{{ .Values.ethstats.image.tag }}{{ if .Values.ethstats.image.digest }}@{{ .Values.ethstats.image.digest }}{{ end }}"
          imagePullPolicy: {{ .Values.ethstats.image.pullPolicy }}
          {{- with .Values.ethstats.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ethstats.service.ports.http }}
              protocol: TCP
          env:
            - name: WS_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.ethstats.secrets.isAwsSecretEnabled }}
                  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-aws-sm-secret
                  {{- else if .Values.ethstats.secrets.data }}
                  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-secret
                  {{- end }}
                  key: "{{ .Values.ethstats.secrets.wsSecretName }}"
            {{- with .Values.ethstats.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.ethstats.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ethstats.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ethstats.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.ethstats.secrets.isAwsSecretEnabled }}
            - name: secrets-store
            {{- else if .Values.ethstats.secrets.data }}
            - name: ws-secret
            {{- end }}
              mountPath: /app/ws_secret
              subPath: ws_secret
              readOnly: true
      volumes:
        {{- if .Values.ethstats.secrets.isAwsSecretEnabled }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-aws-secrets-class
        {{- else if .Values.ethstats.secrets.data }}
        - name: ws-secret
          secret:
            secretName: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-secret
        {{- end }}