{{- if .Values.ethstats.secrets.data }}
{{- $component := "ethstats" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-secret
  namespace: {{ include "linea-dev.namespace" . }}
  labels:
    {{- include "linea-dev.component.labels" (dict "component" $component "root" .) | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.ethstats.secrets.data }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
