{{- if .Values.sequencer.secrets.isAwsSecretEnabled -}}
{{- $component := "sequencer" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-aws-secrets-class
  namespace: {{ include "linea-dev.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    {{- if .Values.global.region }}
    region: {{ .Values.global.region }}
    {{- end }}
    objects: |
      - objectName: "{{ .Values.sequencer.secrets.sequencerKeySecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "{{ .Values.sequencer.secrets.sequencerKeySecretName }}"
            objectAlias: "key"
{{- end }}