{{- if .Values.txgen.enabled }}
{{- $component := "txgen" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea-dev.component.name" (dict "component" $component "root" .) }}-secret
  namespace: {{ include "linea-dev.namespace" . }}
  labels:
    {{- include "linea-dev.component.labels" (dict "component" $component "root" .) | nindent 4 }}
type: Opaque
data:
  SENDER_PK: {{ .Values.txgen.secrets.senderPk | b64enc }}
{{- end }}
